//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowerInGarden
    {
        public int flowerInGardenId { get; set; }
        public int gardenId { get; set; }
        public Nullable<int> wateringId { get; set; }
        public string potType { get; set; }
        public Nullable<int> potSize { get; set; }
        public string flowerName { get; set; }
        public string description { get; set; }
        public string colour { get; set; }
        public string picture { get; set; }
    
        public virtual Gardens Gardens { get; set; }
        public virtual Watering Watering { get; set; }
    }
}
