//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlowerProjectEntities : DbContext
    {
        public FlowerProjectEntities()
            : base("name=FlowerProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FlowerInGarden> FlowerInGarden { get; set; }
        public virtual DbSet<Flowers> Flowers { get; set; }
        public virtual DbSet<Gardens> Gardens { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Watering> Watering { get; set; }
    }
}
